name: build-app

on: push

jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4

      - name: install-package
        run: npm install

      - name: build-app 
        run: npm run build

      - name: start-app
        run: npm start

      - name: test-curl
        run: curl http://localhost:3000

      
